services:
  
  backend:
    build: .
    command: npm run start:dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      redis:
      database: 
        condition: service_healthy
      
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root123}
      - POSTGRES_DB=${POSTGRES_DB:-template_api}
    volumes:
      - dados_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d template_api"]
      interval: 5s
      timeout: 5s
      retries: 5

  regis: 
    image: redis:8.8-m03-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-root123}
    volumes:
      -dados_db:/var/lib/redis/data

volumes:
  dados_db:
